/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Report API readiness */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponse: {
      /** @enum {string} */
      status: "ok";
      /** @enum {string} */
      service: "talent-dna-api";
      /** @example v1 */
      version: string;
    };
    Problem: {
      /**
       * Format: uri-reference
       * @default about:blank
       */
      type: string;
      title: string;
      status: number;
      detail?: string;
      /** Format: uri-reference */
      instance?: string;
      errors?: {
        [key: string]: string[];
      };
    };
  };
  responses: {
    /** @description A problem-details error response. */
    ProblemResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API is ready. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      400: components["responses"]["ProblemResponse"];
      default: components["responses"]["ProblemResponse"];
    };
  };
}
